In [16]:
import numpy as np


generating marks of 10 student of 3 subject 

In [17]:
np.random.seed(42)
marks = np.random.randint(100, size=(10,3))
print("marks of 10 students of math, science and social science:")
print(marks)


marks of 10 students of math, science and social science:
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


Average 

In [18]:
#average_per_student:
avg_per_student = np.mean(marks, axis=1)
print("\nAverage marks per student:")
print(np.around(avg_per_student,2))

#average marks per student
avg_per_subject = np.mean(marks, axis = 0)
print("\naverage marks per subject.")
print(np.around(avg_per_subject,2))


Average marks per student:
[52.33 50.33 80.67 86.67 15.33 46.67 22.33 47.33 54.67 52.33]

average marks per subject.
[49.8 58.7 44.1]

Highest scorer indices per subject (Math, Science, English):
[2 0 3]

Lowest scorer indices per subject (Math, Science, English):
[9 5 6]


highest and lowest in each subject

In [ ]:
highest_scorers = np.argmax(marks,axis=0)
lowest_scorers = np.argmin(marks,axis=0)
print("\nHighest scorer indices per subject (Math, Science, English):")
print(highest_scorers)

print("\nLowest scorer indices per subject (Math, Science, English):")
print(lowest_scorers)

Student with highest marks and lowest marks

In [21]:
#total marks of per student
total_marks = np.sum(marks, axis=1)

highest_total_idx = np.argmax(total_marks) #higest marks
lowest_total_idx = np.argmin(total_marks) # lowest marks
print("\nTotal marks of each student :")
print(total_marks)

print(f"Student {highest_total_idx+1} has the highest total marks = {total_marks[highest_total_idx]} ")
print(f"Student {lowest_total_idx+1} has the lowest total marks = {total_marks[lowest_total_idx]}")



Total marks of each student :
[157 151 242 260  46 140  67 142 164 157]
3
Student4 has the highest total marks = 260 
Student 5 has the lowest total marks = 46
